name: transport_analytics
version: 3.0.0
config-version: 2
profile: transport_analytics

model-paths:
  - models

models:
  transport_analytics:
    gold_marts:
      +materialized: view

clean-targets:
  - target
