-- fleet_mssql.vehicle_status v1: retained SCD2 evidence and physical history.
-- Bronze must retain the source-change evidence promised by the RAW contract.
-- These are new version-owned names. CREATE is intentionally fail-closed so an unexpected
-- pre-existing object is investigated instead of silently adopted or replaced.

CREATE TABLE SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS (
    VEHICLE_ID VARCHAR NOT NULL,
    STATUS VARCHAR,
    DEPOT_ID VARCHAR,
    ROUTE_ID VARCHAR,
    SOURCE_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    SOURCE_OPERATION VARCHAR NOT NULL,
    SOURCE_SEQUENCE NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
    ESF_STREAM_ACTION VARCHAR NOT NULL,
    ESF_STREAM_ISUPDATE BOOLEAN NOT NULL,
    ESF_EVENT_HASH VARCHAR NOT NULL,
    ESF_CAPTURED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY (
    VEHICLE_ID VARCHAR NOT NULL,
    STATUS VARCHAR,
    DEPOT_ID VARCHAR,
    ROUTE_ID VARCHAR,
    SOURCE_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    SOURCE_OPERATION VARCHAR NOT NULL,
    SOURCE_SEQUENCE NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_ACTIVE BOOLEAN NOT NULL,
    ESF_VERSION_HASH VARCHAR NOT NULL,
    ESF_BUILT_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE VIEW SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_CURRENT AS
SELECT *
FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY
WHERE IS_ACTIVE = TRUE;

CREATE STREAM BRONZE.FLEET_MSSQL_VEHICLE_STATUS_V1_STREAM
    ON TABLE BRONZE.FLEET_MSSQL_VEHICLE_STATUS
    APPEND_ONLY = FALSE;
