-- Requires CONTROL migration 110_pipeline_execution_metrics.sql.
-- Canonical metric rule: ROWS_AFFECTED is SQLROWCOUNT for DML_QUERY_ID's primary Silver DML.
CREATE PROCEDURE SILVER.APPLY_FLEET_MSSQL_VEHICLE_STATUS_V1()
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RUN_ID VARCHAR DEFAULT UUID_STRING();
    V_ROWS_READ NUMBER DEFAULT 0;
    V_ROWS_AFFECTED NUMBER DEFAULT 0;
    V_AFFECTED_BUSINESS_KEYS NUMBER DEFAULT 0;
    V_DML_QUERY_ID VARCHAR;
    V_ROWS_INSERTED NUMBER;
    V_ROWS_UPDATED NUMBER;
    V_ROWS_DELETED NUMBER;
    V_DATA_MAX_AT TIMESTAMP_LTZ;
    V_METRICS VARIANT DEFAULT OBJECT_CONSTRUCT();
    V_IDEMPOTENCY_CONFLICTS NUMBER DEFAULT 0;
    E_IDEMPOTENCY_CONFLICT EXCEPTION (
        -20040,
        'Incoming rows share an idempotency identity but disagree on payload.'
    );
    V_EVENTS_INSERTED NUMBER DEFAULT 0;
    V_EVENTS_INSERT_QUERY_ID VARCHAR;
    V_HISTORY_ROWS_DELETED NUMBER DEFAULT 0;
    V_HISTORY_DELETE_QUERY_ID VARCHAR;
    V_HISTORY_ROWS_REBUILT NUMBER DEFAULT 0;
    V_HISTORY_REBUILD_QUERY_ID VARCHAR;
BEGIN
    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_NEW_EVENTS (
    VEHICLE_ID VARCHAR NOT NULL,
    STATUS VARCHAR,
    DEPOT_ID VARCHAR,
    ROUTE_ID VARCHAR,
    SOURCE_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    SOURCE_OPERATION VARCHAR NOT NULL,
    SOURCE_SEQUENCE NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
        ESF_STREAM_ACTION VARCHAR NOT NULL,
        ESF_STREAM_ISUPDATE BOOLEAN NOT NULL
    );

    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_AFFECTED_KEYS (
    VEHICLE_ID VARCHAR
    );

    INSERT INTO CONTROL.PIPELINE_RUN (
        RUN_ID, DATASET_ID, VERSION, STATUS, STARTED_AT, TASK_NAME, WAREHOUSE_NAME,
        METRICS_CONTRACT_VERSION
    )
    SELECT
        :V_RUN_ID, 'fleet_mssql.vehicle_status', 'v1', 'RUNNING',
        CURRENT_TIMESTAMP(), 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_TASK', CURRENT_WAREHOUSE(), 1;
    BEGIN
        BEGIN TRANSACTION;

        INSERT INTO ESF_NEW_EVENTS (VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, ESF_STREAM_ACTION, ESF_STREAM_ISUPDATE)
        SELECT
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT,
            METADATA$ACTION,
            METADATA$ISUPDATE
        FROM BRONZE.FLEET_MSSQL_VEHICLE_STATUS_V1_STREAM
        WHERE NOT (METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE);

        V_ROWS_READ := (SELECT COUNT(*) FROM ESF_NEW_EVENTS);
        V_DATA_MAX_AT := (SELECT MAX(SOURCE_UPDATED_AT) FROM ESF_NEW_EVENTS);

        V_IDEMPOTENCY_CONFLICTS := (
            SELECT COUNT(*)
            FROM (
                SELECT I.VEHICLE_ID, I.SOURCE_SEQUENCE, I.ESF_STREAM_ACTION
                FROM ESF_NEW_EVENTS I
                GROUP BY I.VEHICLE_ID, I.SOURCE_SEQUENCE, I.ESF_STREAM_ACTION
                HAVING COUNT(DISTINCT TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(I.VEHICLE_ID, I.STATUS, I.DEPOT_ID, I.ROUTE_ID, I.SOURCE_UPDATED_AT, I.SOURCE_OPERATION, I.SOURCE_SEQUENCE, I.INGESTED_AT, I.ESF_STREAM_ACTION, I.ESF_STREAM_ISUPDATE))) > 1
            ) AS ESF_IDEMPOTENCY_CONFLICTS
        );
        IF (V_IDEMPOTENCY_CONFLICTS > 0) THEN
            RAISE E_IDEMPOTENCY_CONFLICT;
        END IF;

        INSERT INTO SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS (
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, ESF_STREAM_ACTION, ESF_STREAM_ISUPDATE, ESF_EVENT_HASH, ESF_CAPTURED_AT
        )
        SELECT
            N.VEHICLE_ID, N.STATUS, N.DEPOT_ID, N.ROUTE_ID, N.SOURCE_UPDATED_AT, N.SOURCE_OPERATION, N.SOURCE_SEQUENCE, N.INGESTED_AT,
            N.ESF_STREAM_ACTION,
            N.ESF_STREAM_ISUPDATE,
            TO_VARCHAR(HASH(N.VEHICLE_ID, N.STATUS, N.DEPOT_ID, N.ROUTE_ID, N.SOURCE_UPDATED_AT, N.SOURCE_OPERATION, N.SOURCE_SEQUENCE, N.INGESTED_AT, N.ESF_STREAM_ACTION)),
            CURRENT_TIMESTAMP()
        FROM (
            SELECT D.*
            FROM ESF_NEW_EVENTS D
            QUALIFY ROW_NUMBER() OVER (
                PARTITION BY D.VEHICLE_ID, D.SOURCE_SEQUENCE, D.ESF_STREAM_ACTION
                ORDER BY TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(D.VEHICLE_ID, D.STATUS, D.DEPOT_ID, D.ROUTE_ID, D.SOURCE_UPDATED_AT, D.SOURCE_OPERATION, D.SOURCE_SEQUENCE, D.INGESTED_AT, D.ESF_STREAM_ACTION, D.ESF_STREAM_ISUPDATE))
            ) = 1
        ) N
        WHERE NOT EXISTS (
            SELECT 1
            FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS E
            WHERE E.VEHICLE_ID IS NOT DISTINCT FROM N.VEHICLE_ID AND E.SOURCE_SEQUENCE IS NOT DISTINCT FROM N.SOURCE_SEQUENCE AND E.ESF_STREAM_ACTION IS NOT DISTINCT FROM N.ESF_STREAM_ACTION
        );

        V_EVENTS_INSERTED := SQLROWCOUNT;
        V_EVENTS_INSERT_QUERY_ID := SQLID;

        INSERT INTO ESF_AFFECTED_KEYS (VEHICLE_ID)
        SELECT DISTINCT VEHICLE_ID
        FROM ESF_NEW_EVENTS;

        V_AFFECTED_BUSINESS_KEYS := (SELECT COUNT(*) FROM ESF_AFFECTED_KEYS);

        DELETE FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY H
        USING ESF_AFFECTED_KEYS K
        WHERE H.VEHICLE_ID = K.VEHICLE_ID;

        V_HISTORY_ROWS_DELETED := SQLROWCOUNT;
        V_HISTORY_DELETE_QUERY_ID := SQLID;

        INSERT INTO SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY (
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, VALID_FROM, VALID_TO, IS_ACTIVE, ESF_VERSION_HASH, ESF_BUILT_AT
        )
        WITH ORDERED_EVENTS AS (
            SELECT
                E.*,
                TO_VARCHAR(HASH(E.STATUS, E.DEPOT_ID, E.ROUTE_ID)) AS ESF_STATE_HASH,
                ((E.ESF_STREAM_ACTION = 'DELETE' AND NOT E.ESF_STREAM_ISUPDATE) OR UPPER(COALESCE(TO_VARCHAR(E.SOURCE_OPERATION), '')) IN ('D')) AS ESF_IS_DELETE,
                LAG(TO_VARCHAR(HASH(E.STATUS, E.DEPOT_ID, E.ROUTE_ID))) OVER (
                    PARTITION BY E.VEHICLE_ID
                    ORDER BY E.SOURCE_UPDATED_AT, E.SOURCE_SEQUENCE
                ) AS ESF_PREV_STATE_HASH,
                LAG(((E.ESF_STREAM_ACTION = 'DELETE' AND NOT E.ESF_STREAM_ISUPDATE) OR UPPER(COALESCE(TO_VARCHAR(E.SOURCE_OPERATION), '')) IN ('D'))) OVER (
                    PARTITION BY E.VEHICLE_ID
                    ORDER BY E.SOURCE_UPDATED_AT, E.SOURCE_SEQUENCE
                ) AS ESF_PREV_IS_DELETE
            FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS E
            JOIN ESF_AFFECTED_KEYS K
              ON E.VEHICLE_ID = K.VEHICLE_ID
        ),
        BOUNDARY_EVENTS AS (
            SELECT
                *,
                IFF(
                    ESF_IS_DELETE
                    OR ESF_PREV_STATE_HASH IS NULL
                    OR COALESCE(ESF_PREV_IS_DELETE, FALSE)
                    OR ESF_STATE_HASH <> ESF_PREV_STATE_HASH,
                    TRUE,
                    FALSE
                ) AS ESF_IS_BOUNDARY
            FROM ORDERED_EVENTS
        ),
        VERSION_BOUNDARIES AS (
            SELECT
                *,
                LEAD(SOURCE_UPDATED_AT) OVER (
                    PARTITION BY VEHICLE_ID
                    ORDER BY SOURCE_UPDATED_AT, SOURCE_SEQUENCE
                ) AS ESF_NEXT_BOUNDARY_AT
            FROM BOUNDARY_EVENTS
            WHERE ESF_IS_BOUNDARY
        )
        SELECT
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT,
            SOURCE_UPDATED_AT,
            ESF_NEXT_BOUNDARY_AT,
            ESF_NEXT_BOUNDARY_AT IS NULL,
            ESF_STATE_HASH,
            CURRENT_TIMESTAMP()
        FROM VERSION_BOUNDARIES
        WHERE NOT ESF_IS_DELETE;

        -- The rebuilt history INSERT is the primary published-Silver DML for the canonical
        -- metric. Event-ledger and history-delete work stay explicit in pattern metrics.
        V_HISTORY_ROWS_REBUILT := SQLROWCOUNT;
        V_HISTORY_REBUILD_QUERY_ID := SQLID;
        V_ROWS_AFFECTED := V_HISTORY_ROWS_REBUILT;
        V_DML_QUERY_ID := V_HISTORY_REBUILD_QUERY_ID;
        V_METRICS := OBJECT_CONSTRUCT(
            'events_inserted', V_EVENTS_INSERTED,
            'event_insert_query_id', V_EVENTS_INSERT_QUERY_ID,
            'history_rows_deleted', V_HISTORY_ROWS_DELETED,
            'history_delete_query_id', V_HISTORY_DELETE_QUERY_ID,
            'history_rows_rebuilt', V_HISTORY_ROWS_REBUILT,
            'history_rebuild_query_id', V_HISTORY_REBUILD_QUERY_ID,
            'primary_dml_query_id', V_DML_QUERY_ID
        );
        COMMIT;
    EXCEPTION
        WHEN OTHER THEN
            ROLLBACK;
            UPDATE CONTROL.PIPELINE_RUN
            SET STATUS = 'FAILED',
                COMPLETED_AT = CURRENT_TIMESTAMP(),
                ERROR_CODE = TO_VARCHAR(SQLCODE),
                ERROR_MESSAGE = SQLERRM
            WHERE RUN_ID = :V_RUN_ID;
            RAISE;
    END;

    UPDATE CONTROL.PIPELINE_RUN
    SET STATUS = 'SUCCESS',
        COMPLETED_AT = CURRENT_TIMESTAMP(),
        ROWS_READ = :V_ROWS_READ,
        ROWS_AFFECTED = :V_ROWS_AFFECTED,
        AFFECTED_BUSINESS_KEYS = :V_AFFECTED_BUSINESS_KEYS,
        BRONZE_DATA_MAX_AT = :V_DATA_MAX_AT,
        SILVER_DATA_MAX_AT = :V_DATA_MAX_AT,
        SILVER_PUBLISHED_AT = CURRENT_TIMESTAMP(),
        DML_QUERY_ID = :V_DML_QUERY_ID,
        QUERY_ID = :V_DML_QUERY_ID,
        METRICS_CONTRACT_VERSION = 1,
        METRICS = :V_METRICS,
        -- Legacy breakdown fields are only populated when their meaning is unambiguous.
        ROWS_INSERTED = :V_ROWS_INSERTED,
        ROWS_UPDATED = :V_ROWS_UPDATED,
        ROWS_DELETED = :V_ROWS_DELETED
    WHERE RUN_ID = :V_RUN_ID;
    RETURN OBJECT_CONSTRUCT(
        'run_id', V_RUN_ID,
        'metrics_contract_version', 1,
        'rows_read', V_ROWS_READ,
        'rows_affected', V_ROWS_AFFECTED,
        'affected_business_keys', V_AFFECTED_BUSINESS_KEYS,
        'dml_query_id', V_DML_QUERY_ID,
        'metrics', V_METRICS
    );
END;
$$;
