-- Historical candidate bootstrap/replay.
-- Requires Bronze to retain the full_change/full_event evidence declared by the RAW contract.
-- NULL bounds clear candidate evidence/history and deterministically rebuild all retained history.
-- A bounded replay assumes the candidate already has a correct baseline outside the requested window.
CREATE PROCEDURE SILVER.REPLAY_FLEET_MSSQL_VEHICLE_STATUS_V1(
    P_FROM TIMESTAMP_NTZ DEFAULT NULL,
    P_TO TIMESTAMP_NTZ DEFAULT NULL
)
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_REPAIR_ID VARCHAR DEFAULT UUID_STRING();
    V_ROWS_READ NUMBER DEFAULT 0;
    V_ROWS_RECOVERED NUMBER DEFAULT 0;
    V_IDEMPOTENCY_CONFLICTS NUMBER DEFAULT 0;
    E_IDEMPOTENCY_CONFLICT EXCEPTION (
        -20040,
        'Incoming rows share an idempotency identity but disagree on payload.'
    );
BEGIN
    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_REPLAY_INPUT (
    VEHICLE_ID VARCHAR NOT NULL,
    STATUS VARCHAR,
    DEPOT_ID VARCHAR,
    ROUTE_ID VARCHAR,
    SOURCE_UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    SOURCE_OPERATION VARCHAR NOT NULL,
    SOURCE_SEQUENCE NUMBER NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
        ESF_STREAM_ACTION VARCHAR NOT NULL,
        ESF_STREAM_ISUPDATE BOOLEAN NOT NULL
    );

    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_AFFECTED_KEYS (
    VEHICLE_ID VARCHAR
    );

    INSERT INTO ESF_REPLAY_INPUT (VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, ESF_STREAM_ACTION, ESF_STREAM_ISUPDATE)
    SELECT B.VEHICLE_ID, B.STATUS, B.DEPOT_ID, B.ROUTE_ID, B.SOURCE_UPDATED_AT, B.SOURCE_OPERATION, B.SOURCE_SEQUENCE, B.INGESTED_AT, IFF(UPPER(COALESCE(TO_VARCHAR(B.SOURCE_OPERATION), '')) IN ('D'), 'DELETE', 'INSERT'), FALSE
    FROM BRONZE.FLEET_MSSQL_VEHICLE_STATUS B
    WHERE (:P_FROM IS NULL OR B.SOURCE_UPDATED_AT >= :P_FROM)
      AND (:P_TO IS NULL OR B.SOURCE_UPDATED_AT < :P_TO);

    V_ROWS_READ := (SELECT COUNT(*) FROM ESF_REPLAY_INPUT);

    INSERT INTO CONTROL.REPAIR_RUN (
        REPAIR_ID, DATASET_ID, REPAIR_TYPE, REQUESTED_FROM, REQUESTED_TO, STATUS, STARTED_AT, OPERATOR
    )
    SELECT
        :V_REPAIR_ID, 'fleet_mssql.vehicle_status', 'SILVER_REPLAY', :P_FROM, :P_TO,
        'RUNNING', CURRENT_TIMESTAMP(), CURRENT_USER();

    BEGIN
        BEGIN TRANSACTION;

        V_IDEMPOTENCY_CONFLICTS := (
            SELECT COUNT(*)
            FROM (
                SELECT I.VEHICLE_ID, I.SOURCE_SEQUENCE, I.ESF_STREAM_ACTION
                FROM ESF_REPLAY_INPUT I
                GROUP BY I.VEHICLE_ID, I.SOURCE_SEQUENCE, I.ESF_STREAM_ACTION
                HAVING COUNT(DISTINCT TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(I.VEHICLE_ID, I.STATUS, I.DEPOT_ID, I.ROUTE_ID, I.SOURCE_UPDATED_AT, I.SOURCE_OPERATION, I.SOURCE_SEQUENCE, I.INGESTED_AT, I.ESF_STREAM_ACTION, I.ESF_STREAM_ISUPDATE))) > 1
            ) AS ESF_IDEMPOTENCY_CONFLICTS
        );
        IF (V_IDEMPOTENCY_CONFLICTS > 0) THEN
            RAISE E_IDEMPOTENCY_CONFLICT;
        END IF;

        IF (P_FROM IS NULL AND P_TO IS NULL) THEN
            DELETE FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY;
            DELETE FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS;
        END IF;

        INSERT INTO SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS (
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, ESF_STREAM_ACTION, ESF_STREAM_ISUPDATE, ESF_EVENT_HASH, ESF_CAPTURED_AT
        )
        SELECT
            N.VEHICLE_ID, N.STATUS, N.DEPOT_ID, N.ROUTE_ID, N.SOURCE_UPDATED_AT, N.SOURCE_OPERATION, N.SOURCE_SEQUENCE, N.INGESTED_AT,
            N.ESF_STREAM_ACTION,
            N.ESF_STREAM_ISUPDATE,
            TO_VARCHAR(HASH(N.VEHICLE_ID, N.STATUS, N.DEPOT_ID, N.ROUTE_ID, N.SOURCE_UPDATED_AT, N.SOURCE_OPERATION, N.SOURCE_SEQUENCE, N.INGESTED_AT, N.ESF_STREAM_ACTION)),
            CURRENT_TIMESTAMP()
        FROM (
            SELECT D.*
            FROM ESF_REPLAY_INPUT D
            QUALIFY ROW_NUMBER() OVER (
                PARTITION BY D.VEHICLE_ID, D.SOURCE_SEQUENCE, D.ESF_STREAM_ACTION
                ORDER BY TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(D.VEHICLE_ID, D.STATUS, D.DEPOT_ID, D.ROUTE_ID, D.SOURCE_UPDATED_AT, D.SOURCE_OPERATION, D.SOURCE_SEQUENCE, D.INGESTED_AT, D.ESF_STREAM_ACTION, D.ESF_STREAM_ISUPDATE))
            ) = 1
        ) N
        WHERE NOT EXISTS (
            SELECT 1
            FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS E
            WHERE E.VEHICLE_ID IS NOT DISTINCT FROM N.VEHICLE_ID AND E.SOURCE_SEQUENCE IS NOT DISTINCT FROM N.SOURCE_SEQUENCE AND E.ESF_STREAM_ACTION IS NOT DISTINCT FROM N.ESF_STREAM_ACTION
        );

        INSERT INTO ESF_AFFECTED_KEYS (VEHICLE_ID)
        SELECT DISTINCT B.VEHICLE_ID
        FROM ESF_REPLAY_INPUT B;

        DELETE FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY H
        USING ESF_AFFECTED_KEYS K
        WHERE H.VEHICLE_ID = K.VEHICLE_ID;

        INSERT INTO SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY (
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT, VALID_FROM, VALID_TO, IS_ACTIVE, ESF_VERSION_HASH, ESF_BUILT_AT
        )
        WITH ORDERED_EVENTS AS (
            SELECT
                E.*,
                TO_VARCHAR(HASH(E.STATUS, E.DEPOT_ID, E.ROUTE_ID)) AS ESF_STATE_HASH,
                ((E.ESF_STREAM_ACTION = 'DELETE' AND NOT E.ESF_STREAM_ISUPDATE) OR UPPER(COALESCE(TO_VARCHAR(E.SOURCE_OPERATION), '')) IN ('D')) AS ESF_IS_DELETE,
                LAG(TO_VARCHAR(HASH(E.STATUS, E.DEPOT_ID, E.ROUTE_ID))) OVER (
                    PARTITION BY E.VEHICLE_ID
                    ORDER BY E.SOURCE_UPDATED_AT, E.SOURCE_SEQUENCE
                ) AS ESF_PREV_STATE_HASH,
                LAG(((E.ESF_STREAM_ACTION = 'DELETE' AND NOT E.ESF_STREAM_ISUPDATE) OR UPPER(COALESCE(TO_VARCHAR(E.SOURCE_OPERATION), '')) IN ('D'))) OVER (
                    PARTITION BY E.VEHICLE_ID
                    ORDER BY E.SOURCE_UPDATED_AT, E.SOURCE_SEQUENCE
                ) AS ESF_PREV_IS_DELETE
            FROM SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_EVENTS E
            JOIN ESF_AFFECTED_KEYS K
              ON E.VEHICLE_ID = K.VEHICLE_ID
        ),
        BOUNDARY_EVENTS AS (
            SELECT
                *,
                IFF(
                    ESF_IS_DELETE
                    OR ESF_PREV_STATE_HASH IS NULL
                    OR COALESCE(ESF_PREV_IS_DELETE, FALSE)
                    OR ESF_STATE_HASH <> ESF_PREV_STATE_HASH,
                    TRUE, FALSE
                ) AS ESF_IS_BOUNDARY
            FROM ORDERED_EVENTS
        ),
        VERSION_BOUNDARIES AS (
            SELECT
                *,
                LEAD(SOURCE_UPDATED_AT) OVER (
                    PARTITION BY VEHICLE_ID
                    ORDER BY SOURCE_UPDATED_AT, SOURCE_SEQUENCE
                ) AS ESF_NEXT_BOUNDARY_AT
            FROM BOUNDARY_EVENTS
            WHERE ESF_IS_BOUNDARY
        )
        SELECT
            VEHICLE_ID, STATUS, DEPOT_ID, ROUTE_ID, SOURCE_UPDATED_AT, SOURCE_OPERATION, SOURCE_SEQUENCE, INGESTED_AT,
            SOURCE_UPDATED_AT,
            ESF_NEXT_BOUNDARY_AT,
            ESF_NEXT_BOUNDARY_AT IS NULL,
            ESF_STATE_HASH,
            CURRENT_TIMESTAMP()
        FROM VERSION_BOUNDARIES
        WHERE NOT ESF_IS_DELETE;

        V_ROWS_RECOVERED := SQLROWCOUNT;
        COMMIT;
    EXCEPTION
        WHEN OTHER THEN
            ROLLBACK;
            UPDATE CONTROL.REPAIR_RUN
            SET STATUS = 'FAILED', COMPLETED_AT = CURRENT_TIMESTAMP(),
                ERROR_CODE = TO_VARCHAR(SQLCODE), ERROR_MESSAGE = SQLERRM
            WHERE REPAIR_ID = :V_REPAIR_ID;
            RAISE;
    END;

    UPDATE CONTROL.REPAIR_RUN
    SET STATUS = 'SUCCESS', COMPLETED_AT = CURRENT_TIMESTAMP(), ROWS_RECOVERED = :V_ROWS_RECOVERED
    WHERE REPAIR_ID = :V_REPAIR_ID;

    RETURN OBJECT_CONSTRUCT(
        'repair_id', V_REPAIR_ID,
        'rows_read', V_ROWS_READ,
        'rows_recovered', V_ROWS_RECOVERED
    );
END;
$$;
