-- Register operational identity. This does not route transformation logic.
-- PATTERN belongs to the logical dataset; EXECUTION_MODEL belongs to this implementation version.
MERGE INTO CONTROL.DATASET D
USING (
    SELECT
        'fleet_mssql.vehicle_status' AS DATASET_ID,
        'fleet_mssql' AS SOURCE_ID,
        'vehicle_status' AS DATASET_NAME,
        'transport-data' AS OWNER,
        'scd2' AS PATTERN,
        'BRONZE.FLEET_MSSQL_VEHICLE_STATUS' AS BRONZE_RELATION,
        'SILVER.FLEET_MSSQL_VEHICLE_STATUS_CURRENT' AS PUBLISHED_SILVER_RELATION
) S
ON D.DATASET_ID = S.DATASET_ID
WHEN MATCHED THEN UPDATE SET
    D.OWNER = S.OWNER,
    D.PATTERN = S.PATTERN,
    D.BRONZE_RELATION = S.BRONZE_RELATION,
    D.PUBLISHED_SILVER_RELATION = S.PUBLISHED_SILVER_RELATION,
    D.ACTIVE_VERSION = COALESCE(D.ACTIVE_VERSION, 'v1'),
    D.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    DATASET_ID, SOURCE_ID, DATASET_NAME, OWNER, PATTERN, ENABLED,
    BRONZE_RELATION, PUBLISHED_SILVER_RELATION, ACTIVE_VERSION, CANDIDATE_VERSION
) VALUES (
    S.DATASET_ID, S.SOURCE_ID, S.DATASET_NAME, S.OWNER, S.PATTERN, TRUE,
    S.BRONZE_RELATION, S.PUBLISHED_SILVER_RELATION, 'v1', NULL
);

MERGE INTO CONTROL.DATASET_VERSION V
USING (
    SELECT
        'fleet_mssql.vehicle_status' AS DATASET_ID,
        'v1' AS VERSION,
        'ACTIVE' AS STATUS
) S
ON V.DATASET_ID = S.DATASET_ID AND V.VERSION = S.VERSION
WHEN MATCHED THEN UPDATE SET
    V.STATUS = IFF(V.STATUS = 'ACTIVE', 'ACTIVE', S.STATUS),
    V.HISTORY_RELATION = 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY',
    V.CURRENT_RELATION = 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_CURRENT',
    V.APPLY_OBJECT = 'SILVER.APPLY_FLEET_MSSQL_VEHICLE_STATUS_V1',
    V.TASK_OBJECT = 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_TASK',
    V.STREAM_OBJECT = 'BRONZE.FLEET_MSSQL_VEHICLE_STATUS_V1_STREAM',
    V.EXECUTION_MODEL = 'stream_task',
    V.PRIMARY_RUNTIME_OBJECT = 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_TASK',
    V.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    DATASET_ID, VERSION, STATUS, HISTORY_RELATION, CURRENT_RELATION,
    APPLY_OBJECT, TASK_OBJECT, STREAM_OBJECT, EXECUTION_MODEL, PRIMARY_RUNTIME_OBJECT, DEPLOYED_AT
) VALUES (
    S.DATASET_ID, S.VERSION, S.STATUS, 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_HISTORY', 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_CURRENT',
    'SILVER.APPLY_FLEET_MSSQL_VEHICLE_STATUS_V1', 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_TASK', 'BRONZE.FLEET_MSSQL_VEHICLE_STATUS_V1_STREAM', 'stream_task', 'SILVER.FLEET_MSSQL_VEHICLE_STATUS_V1_TASK', CURRENT_TIMESTAMP()
);
