-- Requires CONTROL migration 110_pipeline_execution_metrics.sql.
-- Canonical metric rule: ROWS_AFFECTED is SQLROWCOUNT for DML_QUERY_ID's primary Silver DML.
CREATE PROCEDURE SILVER.APPLY_GTFS_REALTIME_VEHICLE_POSITION_V1()
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_RUN_ID VARCHAR DEFAULT UUID_STRING();
    V_ROWS_READ NUMBER DEFAULT 0;
    V_ROWS_AFFECTED NUMBER DEFAULT 0;
    V_AFFECTED_BUSINESS_KEYS NUMBER DEFAULT 0;
    V_DML_QUERY_ID VARCHAR;
    V_ROWS_INSERTED NUMBER;
    V_ROWS_UPDATED NUMBER;
    V_ROWS_DELETED NUMBER;
    V_DATA_MAX_AT TIMESTAMP_LTZ;
    V_METRICS VARIANT DEFAULT OBJECT_CONSTRUCT();
    V_IDEMPOTENCY_CONFLICTS NUMBER DEFAULT 0;
    E_IDEMPOTENCY_CONFLICT EXCEPTION (
        -20040,
        'Incoming rows share an idempotency identity but disagree on payload.'
    );
BEGIN
    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_NEW_EVENTS (
    VEHICLE_ID VARCHAR NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ROUTE_ID VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL
    );

    INSERT INTO CONTROL.PIPELINE_RUN (
        RUN_ID, DATASET_ID, VERSION, STATUS, STARTED_AT, TASK_NAME, WAREHOUSE_NAME,
        METRICS_CONTRACT_VERSION
    )
    SELECT
        :V_RUN_ID, 'gtfs_realtime.vehicle_position', 'v1', 'RUNNING',
        CURRENT_TIMESTAMP(), 'SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1_TASK', CURRENT_WAREHOUSE(), 1;
    BEGIN
        BEGIN TRANSACTION;

        INSERT INTO ESF_NEW_EVENTS (VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT)
        SELECT VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT
        FROM BRONZE.GTFS_REALTIME_VEHICLE_POSITION_V1_STREAM
        WHERE METADATA$ACTION = 'INSERT';

        V_ROWS_READ := (SELECT COUNT(*) FROM ESF_NEW_EVENTS);
        V_IDEMPOTENCY_CONFLICTS := (
            SELECT COUNT(*)
            FROM (
                SELECT I.VEHICLE_ID, I.EVENT_TIMESTAMP
                FROM ESF_NEW_EVENTS I
                GROUP BY I.VEHICLE_ID, I.EVENT_TIMESTAMP
                HAVING COUNT(DISTINCT TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(I.VEHICLE_ID, I.EVENT_TIMESTAMP, I.LATITUDE, I.LONGITUDE, I.ROUTE_ID, I.INGESTED_AT))) > 1
            ) AS ESF_IDEMPOTENCY_CONFLICTS
        );
        IF (V_IDEMPOTENCY_CONFLICTS > 0) THEN
            RAISE E_IDEMPOTENCY_CONFLICT;
        END IF;

        V_AFFECTED_BUSINESS_KEYS := (SELECT COUNT(*) FROM (SELECT DISTINCT VEHICLE_ID FROM ESF_NEW_EVENTS));
        V_DATA_MAX_AT := (SELECT MAX(EVENT_TIMESTAMP) FROM ESF_NEW_EVENTS);

        INSERT INTO SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 (VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT, ESF_LOADED_AT)
        SELECT N.VEHICLE_ID, N.EVENT_TIMESTAMP, N.LATITUDE, N.LONGITUDE, N.ROUTE_ID, N.INGESTED_AT, CURRENT_TIMESTAMP()
        FROM (
            SELECT D.*
            FROM ESF_NEW_EVENTS D
            QUALIFY ROW_NUMBER() OVER (
                PARTITION BY D.VEHICLE_ID, D.EVENT_TIMESTAMP
                ORDER BY TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(D.VEHICLE_ID, D.EVENT_TIMESTAMP, D.LATITUDE, D.LONGITUDE, D.ROUTE_ID, D.INGESTED_AT))
            ) = 1
        ) N
        WHERE NOT EXISTS (
            SELECT 1
            FROM SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 T
            WHERE T.VEHICLE_ID IS NOT DISTINCT FROM N.VEHICLE_ID AND T.EVENT_TIMESTAMP IS NOT DISTINCT FROM N.EVENT_TIMESTAMP
        );

        -- Capture DML evidence immediately. Do not call LAST_QUERY_ID() after logging statements.
        V_ROWS_AFFECTED := SQLROWCOUNT;
        V_DML_QUERY_ID := SQLID;
        V_ROWS_INSERTED := V_ROWS_AFFECTED;
        V_ROWS_UPDATED := 0;
        V_ROWS_DELETED := 0;
        V_METRICS := OBJECT_CONSTRUCT(
            'output_rows_inserted', V_ROWS_AFFECTED,
            'primary_dml_query_id', V_DML_QUERY_ID
        );
        COMMIT;
    EXCEPTION
        WHEN OTHER THEN
            ROLLBACK;
            UPDATE CONTROL.PIPELINE_RUN
            SET STATUS = 'FAILED',
                COMPLETED_AT = CURRENT_TIMESTAMP(),
                ERROR_CODE = TO_VARCHAR(SQLCODE),
                ERROR_MESSAGE = SQLERRM
            WHERE RUN_ID = :V_RUN_ID;
            RAISE;
    END;

    UPDATE CONTROL.PIPELINE_RUN
    SET STATUS = 'SUCCESS',
        COMPLETED_AT = CURRENT_TIMESTAMP(),
        ROWS_READ = :V_ROWS_READ,
        ROWS_AFFECTED = :V_ROWS_AFFECTED,
        AFFECTED_BUSINESS_KEYS = :V_AFFECTED_BUSINESS_KEYS,
        BRONZE_DATA_MAX_AT = :V_DATA_MAX_AT,
        SILVER_DATA_MAX_AT = :V_DATA_MAX_AT,
        SILVER_PUBLISHED_AT = CURRENT_TIMESTAMP(),
        DML_QUERY_ID = :V_DML_QUERY_ID,
        QUERY_ID = :V_DML_QUERY_ID,
        METRICS_CONTRACT_VERSION = 1,
        METRICS = :V_METRICS,
        -- Legacy breakdown fields are only populated when their meaning is unambiguous.
        ROWS_INSERTED = :V_ROWS_INSERTED,
        ROWS_UPDATED = :V_ROWS_UPDATED,
        ROWS_DELETED = :V_ROWS_DELETED
    WHERE RUN_ID = :V_RUN_ID;
    RETURN OBJECT_CONSTRUCT(
        'run_id', V_RUN_ID,
        'metrics_contract_version', 1,
        'rows_read', V_ROWS_READ,
        'rows_affected', V_ROWS_AFFECTED,
        'affected_business_keys', V_AFFECTED_BUSINESS_KEYS,
        'dml_query_id', V_DML_QUERY_ID,
        'metrics', V_METRICS
    );
END;
$$;
