-- Candidate append replay. Bronze remains the source of recovery evidence.
-- NULL bounds perform a deterministic full candidate rebuild. A bounded replay assumes the
-- candidate already has a correct baseline outside the requested window.
CREATE PROCEDURE SILVER.REPLAY_GTFS_REALTIME_VEHICLE_POSITION_V1(
    P_FROM TIMESTAMP_NTZ DEFAULT NULL,
    P_TO TIMESTAMP_NTZ DEFAULT NULL
)
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_REPAIR_ID VARCHAR DEFAULT UUID_STRING();
    V_ROWS_READ NUMBER DEFAULT 0;
    V_ROWS_RECOVERED NUMBER DEFAULT 0;
    V_IDEMPOTENCY_CONFLICTS NUMBER DEFAULT 0;
    E_IDEMPOTENCY_CONFLICT EXCEPTION (
        -20040,
        'Incoming rows share an idempotency identity but disagree on payload.'
    );
BEGIN
    CREATE OR REPLACE PROCEDURE SCOPED TEMP TABLE ESF_REPLAY_INPUT (
    VEHICLE_ID VARCHAR NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ROUTE_ID VARCHAR,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL
    );

    INSERT INTO ESF_REPLAY_INPUT (VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT)
    SELECT B.VEHICLE_ID, B.EVENT_TIMESTAMP, B.LATITUDE, B.LONGITUDE, B.ROUTE_ID, B.INGESTED_AT
    FROM BRONZE.GTFS_REALTIME_VEHICLE_POSITION B
    WHERE (:P_FROM IS NULL OR B.EVENT_TIMESTAMP >= :P_FROM)
          AND (:P_TO IS NULL OR B.EVENT_TIMESTAMP < :P_TO);

    V_ROWS_READ := (SELECT COUNT(*) FROM ESF_REPLAY_INPUT);

    INSERT INTO CONTROL.REPAIR_RUN (
        REPAIR_ID, DATASET_ID, REPAIR_TYPE, REQUESTED_FROM, REQUESTED_TO, STATUS, STARTED_AT, OPERATOR
    )
    SELECT
        :V_REPAIR_ID, 'gtfs_realtime.vehicle_position', 'SILVER_REPLAY', :P_FROM, :P_TO,
        'RUNNING', CURRENT_TIMESTAMP(), CURRENT_USER();

    BEGIN
        BEGIN TRANSACTION;

        V_IDEMPOTENCY_CONFLICTS := (
            SELECT COUNT(*)
            FROM (
                SELECT I.VEHICLE_ID, I.EVENT_TIMESTAMP
                FROM ESF_REPLAY_INPUT I
                GROUP BY I.VEHICLE_ID, I.EVENT_TIMESTAMP
                HAVING COUNT(DISTINCT TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(I.VEHICLE_ID, I.EVENT_TIMESTAMP, I.LATITUDE, I.LONGITUDE, I.ROUTE_ID, I.INGESTED_AT))) > 1
            ) AS ESF_IDEMPOTENCY_CONFLICTS
        );
        IF (V_IDEMPOTENCY_CONFLICTS > 0) THEN
            RAISE E_IDEMPOTENCY_CONFLICT;
        END IF;

        IF (P_FROM IS NULL AND P_TO IS NULL) THEN
            DELETE FROM SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1;
        END IF;

        INSERT INTO SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 (VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT, ESF_LOADED_AT)
        SELECT N.VEHICLE_ID, N.EVENT_TIMESTAMP, N.LATITUDE, N.LONGITUDE, N.ROUTE_ID, N.INGESTED_AT, CURRENT_TIMESTAMP()
        FROM (
            SELECT D.*
            FROM ESF_REPLAY_INPUT D
            QUALIFY ROW_NUMBER() OVER (
                PARTITION BY D.VEHICLE_ID, D.EVENT_TIMESTAMP
                ORDER BY TO_JSON(ARRAY_CONSTRUCT_KEEP_NULL(D.VEHICLE_ID, D.EVENT_TIMESTAMP, D.LATITUDE, D.LONGITUDE, D.ROUTE_ID, D.INGESTED_AT))
            ) = 1
        ) N
        WHERE NOT EXISTS (
            SELECT 1
            FROM SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 T
            WHERE T.VEHICLE_ID IS NOT DISTINCT FROM N.VEHICLE_ID AND T.EVENT_TIMESTAMP IS NOT DISTINCT FROM N.EVENT_TIMESTAMP
        );

        V_ROWS_RECOVERED := SQLROWCOUNT;
        COMMIT;
    EXCEPTION
        WHEN OTHER THEN
            ROLLBACK;
            UPDATE CONTROL.REPAIR_RUN
            SET STATUS = 'FAILED', COMPLETED_AT = CURRENT_TIMESTAMP(),
                ERROR_CODE = TO_VARCHAR(SQLCODE), ERROR_MESSAGE = SQLERRM
            WHERE REPAIR_ID = :V_REPAIR_ID;
            RAISE;
    END;

    UPDATE CONTROL.REPAIR_RUN
    SET STATUS = 'SUCCESS', COMPLETED_AT = CURRENT_TIMESTAMP(), ROWS_RECOVERED = :V_ROWS_RECOVERED
    WHERE REPAIR_ID = :V_REPAIR_ID;

    RETURN OBJECT_CONSTRUCT(
        'repair_id', V_REPAIR_ID,
        'rows_read', V_ROWS_READ,
        'rows_recovered', V_ROWS_RECOVERED
    );
END;
$$;
