-- Candidate append replay. Bronze remains the source of recovery evidence.
-- NULL bounds perform a deterministic full candidate rebuild. A bounded replay assumes the
-- candidate already has a correct baseline outside the requested window.
CREATE PROCEDURE SILVER.REPLAY_GTFS_REALTIME_VEHICLE_POSITION_V1(
    P_FROM TIMESTAMP_NTZ DEFAULT NULL,
    P_TO TIMESTAMP_NTZ DEFAULT NULL
)
RETURNS OBJECT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_REPAIR_ID VARCHAR DEFAULT UUID_STRING();
    V_ROWS_READ NUMBER DEFAULT 0;
    V_ROWS_RECOVERED NUMBER DEFAULT 0;
BEGIN
    INSERT INTO CONTROL.REPAIR_RUN (
        REPAIR_ID, DATASET_ID, REPAIR_TYPE, REQUESTED_FROM, REQUESTED_TO, STATUS, STARTED_AT, OPERATOR
    )
    SELECT
        :V_REPAIR_ID, 'gtfs_realtime.vehicle_position', 'SILVER_REPLAY', :P_FROM, :P_TO,
        'RUNNING', CURRENT_TIMESTAMP(), CURRENT_USER();

    BEGIN
        BEGIN TRANSACTION;

        IF (P_FROM IS NULL AND P_TO IS NULL) THEN
            DELETE FROM SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1;
        END IF;

        V_ROWS_READ := (
            SELECT COUNT(*)
            FROM BRONZE.GTFS_REALTIME_VEHICLE_POSITION B
            WHERE (:P_FROM IS NULL OR B.EVENT_TIMESTAMP >= :P_FROM)
          AND (:P_TO IS NULL OR B.EVENT_TIMESTAMP < :P_TO)
        );

        INSERT INTO SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 (VEHICLE_ID, EVENT_TIMESTAMP, LATITUDE, LONGITUDE, ROUTE_ID, INGESTED_AT, ESF_LOADED_AT)
        SELECT B.VEHICLE_ID, B.EVENT_TIMESTAMP, B.LATITUDE, B.LONGITUDE, B.ROUTE_ID, B.INGESTED_AT, CURRENT_TIMESTAMP()
        FROM BRONZE.GTFS_REALTIME_VEHICLE_POSITION B
        WHERE (:P_FROM IS NULL OR B.EVENT_TIMESTAMP >= :P_FROM)
          AND (:P_TO IS NULL OR B.EVENT_TIMESTAMP < :P_TO)
          AND NOT EXISTS (
              SELECT 1
              FROM SILVER.GTFS_REALTIME_VEHICLE_POSITION_V1 T
              WHERE T.VEHICLE_ID = B.VEHICLE_ID AND T.EVENT_TIMESTAMP = B.EVENT_TIMESTAMP
          );

        V_ROWS_RECOVERED := SQLROWCOUNT;
        COMMIT;
    EXCEPTION
        WHEN OTHER THEN
            ROLLBACK;
            UPDATE CONTROL.REPAIR_RUN
            SET STATUS = 'FAILED', COMPLETED_AT = CURRENT_TIMESTAMP(),
                ERROR_CODE = TO_VARCHAR(SQLCODE), ERROR_MESSAGE = SQLERRM
            WHERE REPAIR_ID = :V_REPAIR_ID;
            RAISE;
    END;

    UPDATE CONTROL.REPAIR_RUN
    SET STATUS = 'SUCCESS', COMPLETED_AT = CURRENT_TIMESTAMP(), ROWS_RECOVERED = :V_ROWS_RECOVERED
    WHERE REPAIR_ID = :V_REPAIR_ID;

    RETURN OBJECT_CONSTRUCT(
        'repair_id', V_REPAIR_ID,
        'rows_read', V_ROWS_READ,
        'rows_recovered', V_ROWS_RECOVERED
    );
END;
$$;
