name: Deploy
run-name: Deploy TRANSPORT ${{ inputs.git_sha }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Snowflake environment."
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      git_sha:
        description: "Full 40-character project Git commit SHA from main history to deploy."
        required: true
        type: string

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-transport-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ruizengalways/enterprise-snowflake-data-project-framework/.github/workflows/project-deploy.yml@b1896aa110632e94c21010695ee000c9181d9caf
    with:
      project_code: TRANSPORT
      environment: ${{ inputs.environment }}
      git_sha: ${{ inputs.git_sha }}
      framework_ref: b1896aa110632e94c21010695ee000c9181d9caf
      project_dir: dbt
