name: PR Workspace

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  workspace:
    uses: ruizengalways/enterprise-snowflake-data-project-framework/.github/workflows/pr-workspace.yml@3408025d4280d57c3bbed0c295e1686fa7d950ea
    with:
      project_code: TRANSPORT
      pr_number: ${{ github.event.pull_request.number }}
      action: ${{ github.event.action == 'closed' && 'drop' || 'create' }}
      framework_ref: 3408025d4280d57c3bbed0c295e1686fa7d950ea
