name: PR Workspace

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  workspace:
    uses: ruizengalways/enterprise-snowflake-data-project-framework/.github/workflows/pr-workspace.yml@f21fe2b00c20d56f45d7673ac79ff5aa1029338c
    with:
      project_code: TRANSPORT
      pr_number: ${{ github.event.pull_request.number }}
      action: ${{ github.event.action == 'closed' && 'drop' || 'create' }}
      framework_ref: f21fe2b00c20d56f45d7673ac79ff5aa1029338c
