name: PR Workspace

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  workspace:
    uses: ruizengalways/enterprise-snowflake-data-project-framework/.github/workflows/pr-workspace.yml@50cb4caa328d11e5cff208faddd953362c769695
    with:
      project_code: TRANSPORT
      pr_number: ${{ github.event.pull_request.number }}
      action: ${{ github.event.action == 'closed' && 'drop' || 'create' }}
      framework_ref: 50cb4caa328d11e5cff208faddd953362c769695
